const tempDescription =
  "Lorem ipsum dolor sit, amet consectetur adipisicing elit";

export const featuredList = [
  {
    title: "01 title",
    description: tempDescription,
    image: {},
    rate: "01 rate",
  },
  {
    title: "02 title",
    description: tempDescription,
    image: {},
    rate: "02 rate",
  },
  {
    title: "03 title",
    description: tempDescription,
    image: {},
    rate: "03 rate",
  },
  {
    title: "04 title",
    description: tempDescription,
    image: {},
    rate: "04 rate",
  },
  {
    title: "05 title",
    description: tempDescription,
    image: {},
    rate: "05 rate",
  },
  {
    title: "06 title",
    description: tempDescription,
    image: {},
    rate: "06 rate",
  },
  {
    title: "07 title",
    description: tempDescription,
    image: {},
    rate: "07 rate",
  },
  {
    title: "08 title",
    description: tempDescription,
    image: {},
    rate: "08 rate",
  },
  {
    title: "09 title",
    description: tempDescription,
    image: {},
    rate: "09 rate",
  },
];

export const provinceOptions = [
  { id: 1, value: "bangkok", label: "Bangkok" },
  { id: 2, value: "amnat_charoen", label: "Amnat Charoen" },
  { id: 3, value: "ang_thong", label: "Ang Thong" },
  { id: 4, value: "bueng_kan", label: "Bueng Kan" },
  { id: 5, value: "buriram", label: "Buriram" },
  { id: 6, value: "chachoengsao", label: "Chachoengsao" },
  { id: 7, value: "chai_nat", label: "Chai Nat" },
  { id: 8, value: "chaiyaphum", label: "Chaiyaphum" },
  { id: 9, value: "chanthaburi", label: "Chanthaburi" },
  { id: 10, value: "chiang_mai", label: "Chiang Mai" },
  { id: 11, value: "chiang_rai", label: "Chiang Rai" },
  { id: 12, value: "chonburi", label: "Chonburi" },
  { id: 13, value: "chumphon", label: "Chumphon" },
  { id: 14, value: "kalasin", label: "Kalasin" },
  { id: 15, value: "kamphaeng_phet", label: "Kamphaeng Phet" },
  { id: 16, value: "kanchanaburi", label: "Kanchanaburi" },
  { id: 17, value: "khon_kaen", label: "Khon Kaen" },
  { id: 18, value: "krabi", label: "Krabi" },
  { id: 19, value: "lampang", label: "Lampang" },
  { id: 20, value: "lamphun", label: "Lamphun" },
  { id: 21, value: "loei", label: "Loei" },
  { id: 22, value: "lopburi", label: "Lopburi" },
  { id: 23, value: "mae_hong_son", label: "Mae Hong Son" },
  { id: 24, value: "maha_sarakham", label: "Maha Sarakham" },
  { id: 25, value: "mukdahan", label: "Mukdahan" },
  { id: 26, value: "nakhon_nayok", label: "Nakhon Nayok" },
  { id: 27, value: "nakhon_pathom", label: "Nakhon Pathom" },
  { id: 28, value: "nakhon_phanom", label: "Nakhon Phanom" },
  { id: 29, value: "nakhon_ratchasima", label: "Nakhon Ratchasima" },
  { id: 30, value: "nakhon_sawan", label: "Nakhon Sawan" },
  { id: 31, value: "nakhon_si_thammarat", label: "Nakhon Si Thammarat" },
  { id: 32, value: "nan", label: "Nan" },
  { id: 33, value: "narathiwat", label: "Narathiwat" },
  { id: 34, value: "nong_bua_lamphu", label: "Nong Bua Lamphu" },
  { id: 35, value: "nong_khai", label: "Nong Khai" },
  { id: 36, value: "nonthaburi", label: "Nonthaburi" },
  { id: 37, value: "pathum_thani", label: "Pathum Thani" },
  { id: 38, value: "pattani", label: "Pattani" },
  { id: 39, value: "phang_nga", label: "Phang Nga" },
  { id: 40, value: "phatthalung", label: "Phatthalung" },
  { id: 41, value: "phayao", label: "Phayao" },
  { id: 42, value: "phetchabun", label: "Phetchabun" },
  { id: 43, value: "phetchaburi", label: "Phetchaburi" },
  { id: 44, value: "phichit", label: "Phichit" },
  { id: 45, value: "phitsanulok", label: "Phitsanulok" },
  { id: 46, value: "phra_nakhon_si_ayutthaya", label: "Phra Nakhon Si Ayutthaya", },
  { id: 47, value: "phrae", label: "Phrae" },
  { id: 48, value: "phuket", label: "Phuket" },
  { id: 49, value: "prachinburi", label: "Prachinburi" },
  { id: 50, value: "prachuap_khiri_khan", label: "Prachuap Khiri Khan" },
  { id: 51, value: "ranong", label: "Ranong" },
  { id: 52, value: "ratchaburi", label: "Ratchaburi" },
  { id: 53, value: "rayong", label: "Rayong" },
  { id: 54, value: "roi_et", label: "Roi Et" },
  { id: 55, value: "sa_kaeo", label: "Sa Kaeo" },
  { id: 56, value: "sakon_nakhon", label: "Sakon Nakhon" },
  { id: 57, value: "samut_prakan", label: "Samut Prakan" },
  { id: 58, value: "samut_sakhon", label: "Samut Sakhon" },
  { id: 59, value: "samut_songkhram", label: "Samut Songkhram" },
  { id: 60, value: "saraburi", label: "Saraburi" },
  { id: 61, value: "satun", label: "Satun" },
  { id: 62, value: "sing_buri", label: "Sing Buri" },
  { id: 63, value: "sisaket", label: "Sisaket" },
  { id: 64, value: "songkhla", label: "Songkhla" },
  { id: 65, value: "sukhothai", label: "Sukhothai" },
  { id: 66, value: "suphan_buri", label: "Suphan Buri" },
  { id: 67, value: "surat_thani", label: "Surat Thani" },
  { id: 68, value: "surin", label: "Surin" },
  { id: 69, value: "tak", label: "Tak" },
  { id: 70, value: "trang", label: "Trang" },
  { id: 71, value: "trat", label: "Trat" },
  { id: 72, value: "ubon_ratchathani", label: "Ubon Ratchathani" },
  { id: 73, value: "udon_thani", label: "Udon Thani" },
  { id: 74, value: "uthai_thani", label: "Uthai Thani" },
  { id: 75, value: "uttaradit", label: "Uttaradit" },
  { id: 76, value: "yala", label: "Yala" },
  { id: 77, value: "yasothon", label: "Yasothon" },
];
